ALTER TABLE users
    ADD COLUMN okta_user_id VARCHAR(255) UNIQUE,
    ADD COLUMN email VARCHAR(255),
    ADD COLUMN profile_picture_url TEXT,
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
    ALTER COLUMN enabled SET DEFAULT TRUE;